# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from flickr_python_sdk import Flickr

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        flickr = Flickr(
        )
        self.assertIsNotNone(flickr)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
