# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import flickr_python_sdk
from flickr_python_sdk.model.public_get_photo_exif_response_photo_exif import PublicGetPhotoExifResponsePhotoExif
from flickr_python_sdk import configuration


class TestPublicGetPhotoExifResponsePhotoExif(unittest.TestCase):
    """PublicGetPhotoExifResponsePhotoExif unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
