# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import flickr_python_sdk
from flickr_python_sdk.model.public_get_group_discussion_topics_response import PublicGetGroupDiscussionTopicsResponse
from flickr_python_sdk import configuration


class TestPublicGetGroupDiscussionTopicsResponse(unittest.TestCase):
    """PublicGetGroupDiscussionTopicsResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
