# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from flickr_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from flickr_python_sdk.api_response import AsyncGeneratorResponse
from flickr_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from flickr_python_sdk import schemas  # noqa: F401

from flickr_python_sdk.model.public_get_user_photos_response import PublicGetUserPhotosResponse as PublicGetUserPhotosResponseSchema

from flickr_python_sdk.type.public_get_user_photos_response import PublicGetUserPhotosResponse

from ...api_client import Dictionary
from flickr_python_sdk.pydantic.public_get_user_photos_response import PublicGetUserPhotosResponse as PublicGetUserPhotosResponsePydantic

# Query params
ApiKeySchema = schemas.StrSchema
UserIdSchema = schemas.StrSchema
SafeSearchSchema = schemas.NumberSchema
MinUploadDateSchema = schemas.NumberSchema
MaxUploadDateSchema = schemas.NumberSchema
MinTakenDateSchema = schemas.NumberSchema
MaxTakenDateSchema = schemas.NumberSchema
ContentTypeSchema = schemas.NumberSchema
PrivacyFilterSchema = schemas.NumberSchema
PageSchema = schemas.NumberSchema
PerPageSchema = schemas.NumberSchema
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
        'api_key': typing.Union[ApiKeySchema, str, ],
        'user_id': typing.Union[UserIdSchema, str, ],
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'safe_search': typing.Union[SafeSearchSchema, decimal.Decimal, int, float, ],
        'min_upload_date': typing.Union[MinUploadDateSchema, decimal.Decimal, int, float, ],
        'max_upload_date': typing.Union[MaxUploadDateSchema, decimal.Decimal, int, float, ],
        'min_taken_date': typing.Union[MinTakenDateSchema, decimal.Decimal, int, float, ],
        'max_taken_date': typing.Union[MaxTakenDateSchema, decimal.Decimal, int, float, ],
        'content_type': typing.Union[ContentTypeSchema, decimal.Decimal, int, float, ],
        'privacy_filter': typing.Union[PrivacyFilterSchema, decimal.Decimal, int, float, ],
        'page': typing.Union[PageSchema, decimal.Decimal, int, float, ],
        'per_page': typing.Union[PerPageSchema, decimal.Decimal, int, float, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_api_key = api_client.QueryParameter(
    name="api_key",
    style=api_client.ParameterStyle.FORM,
    schema=ApiKeySchema,
    required=True,
    explode=True,
)
request_query_user_id = api_client.QueryParameter(
    name="user_id",
    style=api_client.ParameterStyle.FORM,
    schema=UserIdSchema,
    required=True,
    explode=True,
)
request_query_safe_search = api_client.QueryParameter(
    name="safe_search",
    style=api_client.ParameterStyle.FORM,
    schema=SafeSearchSchema,
    explode=True,
)
request_query_min_upload_date = api_client.QueryParameter(
    name="min_upload_date",
    style=api_client.ParameterStyle.FORM,
    schema=MinUploadDateSchema,
    explode=True,
)
request_query_max_upload_date = api_client.QueryParameter(
    name="max_upload_date",
    style=api_client.ParameterStyle.FORM,
    schema=MaxUploadDateSchema,
    explode=True,
)
request_query_min_taken_date = api_client.QueryParameter(
    name="min_taken_date",
    style=api_client.ParameterStyle.FORM,
    schema=MinTakenDateSchema,
    explode=True,
)
request_query_max_taken_date = api_client.QueryParameter(
    name="max_taken_date",
    style=api_client.ParameterStyle.FORM,
    schema=MaxTakenDateSchema,
    explode=True,
)
request_query_content_type = api_client.QueryParameter(
    name="content_type",
    style=api_client.ParameterStyle.FORM,
    schema=ContentTypeSchema,
    explode=True,
)
request_query_privacy_filter = api_client.QueryParameter(
    name="privacy_filter",
    style=api_client.ParameterStyle.FORM,
    schema=PrivacyFilterSchema,
    explode=True,
)
request_query_page = api_client.QueryParameter(
    name="page",
    style=api_client.ParameterStyle.FORM,
    schema=PageSchema,
    explode=True,
)
request_query_per_page = api_client.QueryParameter(
    name="per_page",
    style=api_client.ParameterStyle.FORM,
    schema=PerPageSchema,
    explode=True,
)
SchemaFor200ResponseBodyApplicationJson = PublicGetUserPhotosResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: PublicGetUserPhotosResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: PublicGetUserPhotosResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _get_user_photos_mapped_args(
        self,
        api_key: str,
        user_id: str,
        safe_search: typing.Optional[typing.Union[int, float]] = None,
        min_upload_date: typing.Optional[typing.Union[int, float]] = None,
        max_upload_date: typing.Optional[typing.Union[int, float]] = None,
        min_taken_date: typing.Optional[typing.Union[int, float]] = None,
        max_taken_date: typing.Optional[typing.Union[int, float]] = None,
        content_type: typing.Optional[typing.Union[int, float]] = None,
        privacy_filter: typing.Optional[typing.Union[int, float]] = None,
        page: typing.Optional[typing.Union[int, float]] = None,
        per_page: typing.Optional[typing.Union[int, float]] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        if api_key is not None:
            _query_params["api_key"] = api_key
        if user_id is not None:
            _query_params["user_id"] = user_id
        if safe_search is not None:
            _query_params["safe_search"] = safe_search
        if min_upload_date is not None:
            _query_params["min_upload_date"] = min_upload_date
        if max_upload_date is not None:
            _query_params["max_upload_date"] = max_upload_date
        if min_taken_date is not None:
            _query_params["min_taken_date"] = min_taken_date
        if max_taken_date is not None:
            _query_params["max_taken_date"] = max_taken_date
        if content_type is not None:
            _query_params["content_type"] = content_type
        if privacy_filter is not None:
            _query_params["privacy_filter"] = privacy_filter
        if page is not None:
            _query_params["page"] = page
        if per_page is not None:
            _query_params["per_page"] = per_page
        args.query = _query_params
        return args

    async def _aget_user_photos_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_api_key,
            request_query_user_id,
            request_query_safe_search,
            request_query_min_upload_date,
            request_query_max_upload_date,
            request_query_min_taken_date,
            request_query_max_taken_date,
            request_query_content_type,
            request_query_privacy_filter,
            request_query_page,
            request_query_per_page,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/rest?method=flickr.people.getPhotos',
            headers=_headers,
        )
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _get_user_photos_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_api_key,
            request_query_user_id,
            request_query_safe_search,
            request_query_min_upload_date,
            request_query_max_upload_date,
            request_query_min_taken_date,
            request_query_max_taken_date,
            request_query_content_type,
            request_query_privacy_filter,
            request_query_page,
            request_query_per_page,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/rest?method=flickr.people.getPhotos',
            headers=_headers,
        )
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class GetUserPhotosRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aget_user_photos(
        self,
        api_key: str,
        user_id: str,
        safe_search: typing.Optional[typing.Union[int, float]] = None,
        min_upload_date: typing.Optional[typing.Union[int, float]] = None,
        max_upload_date: typing.Optional[typing.Union[int, float]] = None,
        min_taken_date: typing.Optional[typing.Union[int, float]] = None,
        max_taken_date: typing.Optional[typing.Union[int, float]] = None,
        content_type: typing.Optional[typing.Union[int, float]] = None,
        privacy_filter: typing.Optional[typing.Union[int, float]] = None,
        page: typing.Optional[typing.Union[int, float]] = None,
        per_page: typing.Optional[typing.Union[int, float]] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_user_photos_mapped_args(
            api_key=api_key,
            user_id=user_id,
            safe_search=safe_search,
            min_upload_date=min_upload_date,
            max_upload_date=max_upload_date,
            min_taken_date=min_taken_date,
            max_taken_date=max_taken_date,
            content_type=content_type,
            privacy_filter=privacy_filter,
            page=page,
            per_page=per_page,
        )
        return await self._aget_user_photos_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def get_user_photos(
        self,
        api_key: str,
        user_id: str,
        safe_search: typing.Optional[typing.Union[int, float]] = None,
        min_upload_date: typing.Optional[typing.Union[int, float]] = None,
        max_upload_date: typing.Optional[typing.Union[int, float]] = None,
        min_taken_date: typing.Optional[typing.Union[int, float]] = None,
        max_taken_date: typing.Optional[typing.Union[int, float]] = None,
        content_type: typing.Optional[typing.Union[int, float]] = None,
        privacy_filter: typing.Optional[typing.Union[int, float]] = None,
        page: typing.Optional[typing.Union[int, float]] = None,
        per_page: typing.Optional[typing.Union[int, float]] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_user_photos_mapped_args(
            api_key=api_key,
            user_id=user_id,
            safe_search=safe_search,
            min_upload_date=min_upload_date,
            max_upload_date=max_upload_date,
            min_taken_date=min_taken_date,
            max_taken_date=max_taken_date,
            content_type=content_type,
            privacy_filter=privacy_filter,
            page=page,
            per_page=per_page,
        )
        return self._get_user_photos_oapg(
            query_params=args.query,
        )

class GetUserPhotos(BaseApi):

    async def aget_user_photos(
        self,
        api_key: str,
        user_id: str,
        safe_search: typing.Optional[typing.Union[int, float]] = None,
        min_upload_date: typing.Optional[typing.Union[int, float]] = None,
        max_upload_date: typing.Optional[typing.Union[int, float]] = None,
        min_taken_date: typing.Optional[typing.Union[int, float]] = None,
        max_taken_date: typing.Optional[typing.Union[int, float]] = None,
        content_type: typing.Optional[typing.Union[int, float]] = None,
        privacy_filter: typing.Optional[typing.Union[int, float]] = None,
        page: typing.Optional[typing.Union[int, float]] = None,
        per_page: typing.Optional[typing.Union[int, float]] = None,
        validate: bool = False,
        **kwargs,
    ) -> PublicGetUserPhotosResponsePydantic:
        raw_response = await self.raw.aget_user_photos(
            api_key=api_key,
            user_id=user_id,
            safe_search=safe_search,
            min_upload_date=min_upload_date,
            max_upload_date=max_upload_date,
            min_taken_date=min_taken_date,
            max_taken_date=max_taken_date,
            content_type=content_type,
            privacy_filter=privacy_filter,
            page=page,
            per_page=per_page,
            **kwargs,
        )
        if validate:
            return PublicGetUserPhotosResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(PublicGetUserPhotosResponsePydantic, raw_response.body)
    
    
    def get_user_photos(
        self,
        api_key: str,
        user_id: str,
        safe_search: typing.Optional[typing.Union[int, float]] = None,
        min_upload_date: typing.Optional[typing.Union[int, float]] = None,
        max_upload_date: typing.Optional[typing.Union[int, float]] = None,
        min_taken_date: typing.Optional[typing.Union[int, float]] = None,
        max_taken_date: typing.Optional[typing.Union[int, float]] = None,
        content_type: typing.Optional[typing.Union[int, float]] = None,
        privacy_filter: typing.Optional[typing.Union[int, float]] = None,
        page: typing.Optional[typing.Union[int, float]] = None,
        per_page: typing.Optional[typing.Union[int, float]] = None,
        validate: bool = False,
    ) -> PublicGetUserPhotosResponsePydantic:
        raw_response = self.raw.get_user_photos(
            api_key=api_key,
            user_id=user_id,
            safe_search=safe_search,
            min_upload_date=min_upload_date,
            max_upload_date=max_upload_date,
            min_taken_date=min_taken_date,
            max_taken_date=max_taken_date,
            content_type=content_type,
            privacy_filter=privacy_filter,
            page=page,
            per_page=per_page,
        )
        if validate:
            return PublicGetUserPhotosResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(PublicGetUserPhotosResponsePydantic, raw_response.body)


class ApiForget(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aget(
        self,
        api_key: str,
        user_id: str,
        safe_search: typing.Optional[typing.Union[int, float]] = None,
        min_upload_date: typing.Optional[typing.Union[int, float]] = None,
        max_upload_date: typing.Optional[typing.Union[int, float]] = None,
        min_taken_date: typing.Optional[typing.Union[int, float]] = None,
        max_taken_date: typing.Optional[typing.Union[int, float]] = None,
        content_type: typing.Optional[typing.Union[int, float]] = None,
        privacy_filter: typing.Optional[typing.Union[int, float]] = None,
        page: typing.Optional[typing.Union[int, float]] = None,
        per_page: typing.Optional[typing.Union[int, float]] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_user_photos_mapped_args(
            api_key=api_key,
            user_id=user_id,
            safe_search=safe_search,
            min_upload_date=min_upload_date,
            max_upload_date=max_upload_date,
            min_taken_date=min_taken_date,
            max_taken_date=max_taken_date,
            content_type=content_type,
            privacy_filter=privacy_filter,
            page=page,
            per_page=per_page,
        )
        return await self._aget_user_photos_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def get(
        self,
        api_key: str,
        user_id: str,
        safe_search: typing.Optional[typing.Union[int, float]] = None,
        min_upload_date: typing.Optional[typing.Union[int, float]] = None,
        max_upload_date: typing.Optional[typing.Union[int, float]] = None,
        min_taken_date: typing.Optional[typing.Union[int, float]] = None,
        max_taken_date: typing.Optional[typing.Union[int, float]] = None,
        content_type: typing.Optional[typing.Union[int, float]] = None,
        privacy_filter: typing.Optional[typing.Union[int, float]] = None,
        page: typing.Optional[typing.Union[int, float]] = None,
        per_page: typing.Optional[typing.Union[int, float]] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_user_photos_mapped_args(
            api_key=api_key,
            user_id=user_id,
            safe_search=safe_search,
            min_upload_date=min_upload_date,
            max_upload_date=max_upload_date,
            min_taken_date=min_taken_date,
            max_taken_date=max_taken_date,
            content_type=content_type,
            privacy_filter=privacy_filter,
            page=page,
            per_page=per_page,
        )
        return self._get_user_photos_oapg(
            query_params=args.query,
        )

