# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredContextPhoto(TypedDict):
    pass

class OptionalContextPhoto(TypedDict, total=False):
    title: str

    farm: str

    id: str

    is_faved: bool

    license: int

    media: str

    owner: str

    safe: bool

    secret: str

    server: str

    thumb: str

    url: str

class ContextPhoto(RequiredContextPhoto, OptionalContextPhoto):
    pass
