# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredGroupRestrictions(TypedDict):
    pass

class OptionalGroupRestrictions(TypedDict, total=False):
    art_ok: bool

    has_geo: bool

    images_ok: bool

    moderate_ok: bool

    photos_ok: bool

    restricted_ok: bool

    safe_ok: bool

    screens_ok: bool

    videos_ok: bool

class GroupRestrictions(RequiredGroupRestrictions, OptionalGroupRestrictions):
    pass
