# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredOwner(TypedDict):
    pass

class OptionalOwner(TypedDict, total=False):
    iconfarm: str

    iconserver: str

    is_ad_free: bool

    ispro: bool

    location: str

    noindexfollow: bool

    nsid: str

    path_alias: str

    realname: str

    username: str

class Owner(RequiredOwner, OptionalOwner):
    pass
