# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from flickr_python_sdk.type.cover import Cover
from flickr_python_sdk.type.person_description import PersonDescription
from flickr_python_sdk.type.person_disable_keyboard_shortcuts import PersonDisableKeyboardShortcuts
from flickr_python_sdk.type.person_location import PersonLocation
from flickr_python_sdk.type.person_mbox_sha1_sum import PersonMboxSha1Sum
from flickr_python_sdk.type.person_mobileurl import PersonMobileurl
from flickr_python_sdk.type.person_photos import PersonPhotos
from flickr_python_sdk.type.person_photosurl import PersonPhotosurl
from flickr_python_sdk.type.person_profileurl import PersonProfileurl
from flickr_python_sdk.type.person_realname import PersonRealname
from flickr_python_sdk.type.person_timezone import PersonTimezone
from flickr_python_sdk.type.person_unread_messages import PersonUnreadMessages
from flickr_python_sdk.type.person_username import PersonUsername
from flickr_python_sdk.type.photo_urls import PhotoURLs

class RequiredPerson(TypedDict):
    pass

class OptionalPerson(TypedDict, total=False):
    description: PersonDescription

    can_buy_pro: bool

    cover: Cover

    coverphoto: PhotoURLs

    coverphoto_farm: str

    coverphoto_server: str

    disable_keyboard_shortcuts: PersonDisableKeyboardShortcuts

    expire: bool

    has_stats: bool

    iconfarm: str

    iconserver: str

    id: str

    is_ad_free: bool

    ispro: bool

    location: PersonLocation

    mbox_sha1sum: PersonMboxSha1Sum

    mobileurl: PersonMobileurl

    nsid: str

    path_alias: str

    photos: PersonPhotos

    photosurl: PersonPhotosurl

    profileurl: PersonProfileurl

    realname: PersonRealname

    timezone: PersonTimezone

    unread_messages: PersonUnreadMessages

    user_secret: str

    username: PersonUsername

    yintl: str

class Person(RequiredPerson, OptionalPerson):
    pass
