# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from flickr_python_sdk.type.owner import Owner
from flickr_python_sdk.type.photo_comments import PhotoComments
from flickr_python_sdk.type.photo_dates import PhotoDates
from flickr_python_sdk.type.photo_description import PhotoDescription
from flickr_python_sdk.type.photo_editability import PhotoEditability
from flickr_python_sdk.type.photo_notes import PhotoNotes
from flickr_python_sdk.type.photo_people import PhotoPeople
from flickr_python_sdk.type.photo_permissions import PhotoPermissions
from flickr_python_sdk.type.photo_publiceditability import PhotoPubliceditability
from flickr_python_sdk.type.photo_tags import PhotoTags
from flickr_python_sdk.type.photo_title import PhotoTitle
from flickr_python_sdk.type.photo_urls import PhotoUrls
from flickr_python_sdk.type.photo_usage import PhotoUsage
from flickr_python_sdk.type.photo_visibility import PhotoVisibility

class RequiredPhoto(TypedDict):
    pass

class OptionalPhoto(TypedDict, total=False):
    tags: PhotoTags

    title: PhotoTitle

    description: PhotoDescription

    comments: PhotoComments

    dates: PhotoDates

    dateuploaded: str

    editability: PhotoEditability

    farm: str

    id: str

    isfavorite: bool

    license: str

    media: str

    notes: PhotoNotes

    originalsecret: str

    owner: Owner

    people: PhotoPeople

    permissions: PhotoPermissions

    publiceditability: PhotoPubliceditability

    rotation: str

    safe: bool

    safety_level: str

    secret: str

    server: str

    urls: PhotoUrls

    usage: PhotoUsage

    views: str

    visibility: PhotoVisibility

class Photo(RequiredPhoto, OptionalPhoto):
    pass
