# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from flickr_python_sdk.type.context_photo import ContextPhoto
from flickr_python_sdk.type.public_get_photo_set_context_response_count import PublicGetPhotoSetContextResponseCount

class RequiredPublicGetPhotoSetContextResponse(TypedDict):
    pass

class OptionalPublicGetPhotoSetContextResponse(TypedDict, total=False):
    count: PublicGetPhotoSetContextResponseCount

    nextphoto: ContextPhoto

    prevphoto: ContextPhoto

    stat: str

class PublicGetPhotoSetContextResponse(RequiredPublicGetPhotoSetContextResponse, OptionalPublicGetPhotoSetContextResponse):
    pass
