# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPublicUploadPhotoRequest(TypedDict):
    api_key: str

    photo: typing.IO

class OptionalPublicUploadPhotoRequest(TypedDict, total=False):
    tags: str

    title: str

    description: str

    content_type: str

    hidden: str

    is_family: str

    is_friend: str

    is_public: str

    safety_level: str

class PublicUploadPhotoRequest(RequiredPublicUploadPhotoRequest, OptionalPublicUploadPhotoRequest):
    pass
