# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from flickr_python_sdk.type.topic import Topic

class RequiredPublicGetGroupDiscussionTopicsResponse(TypedDict):
    pass

class OptionalPublicGetGroupDiscussionTopicsResponse(TypedDict, total=False):
    iconfarm: typing.Union[int, float]

    iconserver: typing.Union[int, float]

    ispoolmoderated: bool

    lang: str

    members: typing.Union[int, float]

    name: str

    page: typing.Union[int, float]

    pages: typing.Union[int, float]

    per_page: typing.Union[int, float]

    privacy: typing.Union[int, float]

    topics: typing.List[Topic]

    total: typing.Union[int, float]

class PublicGetGroupDiscussionTopicsResponse(RequiredPublicGetGroupDiscussionTopicsResponse, OptionalPublicGetGroupDiscussionTopicsResponse):
    pass
