# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredSize(TypedDict):
    pass

class OptionalSize(TypedDict, total=False):
    height: typing.Union[int, float]

    label: str

    media: str

    source: str

    url: str

    width: typing.Union[int, float]

class Size(RequiredSize, OptionalSize):
    pass
