# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from flickr_python_sdk.type.topic_message import TopicMessage

class RequiredTopic(TypedDict):
    pass

class OptionalTopic(TypedDict, total=False):
    author: str

    author_is_deleted: bool

    author_path_alias: str

    authorname: str

    can_delete: bool

    can_edit: bool

    can_reply: bool

    count_replies: int

    datecreate: str

    datelastpost: str

    iconfarm: str

    iconserver: str

    id: str

    is_locked: bool

    is_pro: bool

    is_sticky: bool

    last_reply: str

    lastedit: str

    message: TopicMessage

    role: str

    subject: str

class Topic(RequiredTopic, OptionalTopic):
    pass
