# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class Cover(BaseModel):
    title: typing.Optional[str] = Field(None, alias='title')

    farm: typing.Optional[str] = Field(None, alias='farm')

    id: typing.Optional[str] = Field(None, alias='id')

    isfamily: typing.Optional[bool] = Field(None, alias='isfamily')

    isfriend: typing.Optional[bool] = Field(None, alias='isfriend')

    ispublic: typing.Optional[bool] = Field(None, alias='ispublic')

    owner: typing.Optional[str] = Field(None, alias='owner')

    secret: typing.Optional[str] = Field(None, alias='secret')

    server: typing.Optional[str] = Field(None, alias='server')

    y: typing.Optional[str] = Field(None, alias='y')
    class Config:
        arbitrary_types_allowed = True
