# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class GroupRestrictions(BaseModel):
    art_ok: typing.Optional[bool] = Field(None, alias='art_ok')

    has_geo: typing.Optional[bool] = Field(None, alias='has_geo')

    images_ok: typing.Optional[bool] = Field(None, alias='images_ok')

    moderate_ok: typing.Optional[bool] = Field(None, alias='moderate_ok')

    photos_ok: typing.Optional[bool] = Field(None, alias='photos_ok')

    restricted_ok: typing.Optional[bool] = Field(None, alias='restricted_ok')

    safe_ok: typing.Optional[bool] = Field(None, alias='safe_ok')

    screens_ok: typing.Optional[bool] = Field(None, alias='screens_ok')

    videos_ok: typing.Optional[bool] = Field(None, alias='videos_ok')
    class Config:
        arbitrary_types_allowed = True
