# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class Owner(BaseModel):
    iconfarm: typing.Optional[str] = Field(None, alias='iconfarm')

    iconserver: typing.Optional[str] = Field(None, alias='iconserver')

    is_ad_free: typing.Optional[bool] = Field(None, alias='is_ad_free')

    ispro: typing.Optional[bool] = Field(None, alias='ispro')

    location: typing.Optional[str] = Field(None, alias='location')

    noindexfollow: typing.Optional[bool] = Field(None, alias='noindexfollow')

    nsid: typing.Optional[str] = Field(None, alias='nsid')

    path_alias: typing.Optional[str] = Field(None, alias='path_alias')

    realname: typing.Optional[str] = Field(None, alias='realname')

    username: typing.Optional[str] = Field(None, alias='username')
    class Config:
        arbitrary_types_allowed = True
