# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from flickr_python_sdk.pydantic.person_photos_count import PersonPhotosCount
from flickr_python_sdk.pydantic.person_photos_firstdate import PersonPhotosFirstdate
from flickr_python_sdk.pydantic.person_photos_firstdatetaken import PersonPhotosFirstdatetaken
from flickr_python_sdk.pydantic.person_photos_views import PersonPhotosViews

class PersonPhotos(BaseModel):
    count: typing.Optional[PersonPhotosCount] = Field(None, alias='count')

    firstdate: typing.Optional[PersonPhotosFirstdate] = Field(None, alias='firstdate')

    firstdatetaken: typing.Optional[PersonPhotosFirstdatetaken] = Field(None, alias='firstdatetaken')

    views: typing.Optional[PersonPhotosViews] = Field(None, alias='views')
    class Config:
        arbitrary_types_allowed = True
