# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class PhotoDates(BaseModel):
    lastupdate: typing.Optional[str] = Field(None, alias='lastupdate')

    posted: typing.Optional[str] = Field(None, alias='posted')

    taken: typing.Optional[str] = Field(None, alias='taken')

    takengranularity: typing.Optional[str] = Field(None, alias='takengranularity')

    takenunknown: typing.Optional[bool] = Field(None, alias='takenunknown')
    class Config:
        arbitrary_types_allowed = True
