# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from flickr_python_sdk.pydantic.size import Size

class PublicGetPhotoSizesResponseSizes(BaseModel):
    canblog: typing.Optional[typing.Union[int, float]] = Field(None, alias='canblog')

    candownload: typing.Optional[typing.Union[int, float]] = Field(None, alias='candownload')

    canprint: typing.Optional[typing.Union[int, float]] = Field(None, alias='canprint')

    sizes: typing.Optional[typing.List[Size]] = Field(None, alias='sizes')
    class Config:
        arbitrary_types_allowed = True
