# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from flickr_python_sdk.pydantic.context_photo import ContextPhoto
from flickr_python_sdk.pydantic.public_get_photo_set_context_response_count import PublicGetPhotoSetContextResponseCount

class PublicGetPhotoSetContextResponse(BaseModel):
    count: typing.Optional[PublicGetPhotoSetContextResponseCount] = Field(None, alias='count')

    nextphoto: typing.Optional[ContextPhoto] = Field(None, alias='nextphoto')

    prevphoto: typing.Optional[ContextPhoto] = Field(None, alias='prevphoto')

    stat: typing.Optional[str] = Field(None, alias='stat')
    class Config:
        arbitrary_types_allowed = True
