# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from flickr_python_sdk.pydantic.topic import Topic

class PublicGetGroupDiscussionTopicsResponse(BaseModel):
    iconfarm: typing.Optional[typing.Union[int, float]] = Field(None, alias='iconfarm')

    iconserver: typing.Optional[typing.Union[int, float]] = Field(None, alias='iconserver')

    ispoolmoderated: typing.Optional[bool] = Field(None, alias='ispoolmoderated')

    lang: typing.Optional[str] = Field(None, alias='lang')

    members: typing.Optional[typing.Union[int, float]] = Field(None, alias='members')

    name: typing.Optional[str] = Field(None, alias='name')

    page: typing.Optional[typing.Union[int, float]] = Field(None, alias='page')

    pages: typing.Optional[typing.Union[int, float]] = Field(None, alias='pages')

    per_page: typing.Optional[typing.Union[int, float]] = Field(None, alias='per_page')

    privacy: typing.Optional[typing.Union[int, float]] = Field(None, alias='privacy')

    topics: typing.Optional[typing.List[Topic]] = Field(None, alias='topics')

    total: typing.Optional[typing.Union[int, float]] = Field(None, alias='total')
    class Config:
        arbitrary_types_allowed = True
