# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class PublicUploadPhotoRequest(BaseModel):
    api_key: str = Field(alias='api_key')

    photo: typing.IO = Field(alias='photo')

    tags: typing.Optional[str] = Field(None, alias='tags')

    title: typing.Optional[str] = Field(None, alias='title')

    description: typing.Optional[str] = Field(None, alias='description')

    content_type: typing.Optional[Literal["1", "2", "3"]] = Field(None, alias='content_type')

    hidden: typing.Optional[Literal["1", "2"]] = Field(None, alias='hidden')

    is_family: typing.Optional[Literal["0", "1"]] = Field(None, alias='is_family')

    is_friend: typing.Optional[Literal["0", "1"]] = Field(None, alias='is_friend')

    is_public: typing.Optional[Literal["0", "1"]] = Field(None, alias='is_public')

    safety_level: typing.Optional[Literal["1", "2", "3"]] = Field(None, alias='safety_level')
    class Config:
        arbitrary_types_allowed = True
