# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class Size(BaseModel):
    height: typing.Optional[typing.Union[int, float]] = Field(None, alias='height')

    label: typing.Optional[str] = Field(None, alias='label')

    media: typing.Optional[str] = Field(None, alias='media')

    source: typing.Optional[str] = Field(None, alias='source')

    url: typing.Optional[str] = Field(None, alias='url')

    width: typing.Optional[typing.Union[int, float]] = Field(None, alias='width')
    class Config:
        arbitrary_types_allowed = True
