# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class Tag(BaseModel):
    _content: typing.Optional[str] = Field(None, alias='_content')

    author: typing.Optional[str] = Field(None, alias='author')

    authorname: typing.Optional[str] = Field(None, alias='authorname')

    id: typing.Optional[str] = Field(None, alias='id')

    machine_tag: typing.Optional[bool] = Field(None, alias='machine_tag')

    raw: typing.Optional[str] = Field(None, alias='raw')
    class Config:
        arbitrary_types_allowed = True
