# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from flickr_python_sdk.pydantic.topic_reply_message import TopicReplyMessage

class TopicReply(BaseModel):
    author: typing.Optional[str] = Field(None, alias='author')

    author_is_deleted: typing.Optional[bool] = Field(None, alias='author_is_deleted')

    author_path_alias: typing.Optional[str] = Field(None, alias='author_path_alias')

    authorname: typing.Optional[str] = Field(None, alias='authorname')

    can_delete: typing.Optional[bool] = Field(None, alias='can_delete')

    can_edit: typing.Optional[bool] = Field(None, alias='can_edit')

    datecreate: typing.Optional[str] = Field(None, alias='datecreate')

    iconfarm: typing.Optional[str] = Field(None, alias='iconfarm')

    iconserver: typing.Optional[str] = Field(None, alias='iconserver')

    id: typing.Optional[str] = Field(None, alias='id')

    is_pro: typing.Optional[bool] = Field(None, alias='is_pro')

    lastedit: typing.Optional[str] = Field(None, alias='lastedit')

    message: typing.Optional[TopicReplyMessage] = Field(None, alias='message')
    class Config:
        arbitrary_types_allowed = True
