# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from flickr_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from flickr_python_sdk.api_response import AsyncGeneratorResponse
from flickr_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from flickr_python_sdk import schemas  # noqa: F401

from flickr_python_sdk.model.public_upload_photo_request import PublicUploadPhotoRequest as PublicUploadPhotoRequestSchema

from flickr_python_sdk.type.public_upload_photo_request import PublicUploadPhotoRequest

from ...api_client import Dictionary
from flickr_python_sdk.pydantic.public_upload_photo_request import PublicUploadPhotoRequest as PublicUploadPhotoRequestPydantic

# body param
SchemaForRequestBodyMultipartFormData = PublicUploadPhotoRequestSchema


request_body_public_upload_photo_request = api_client.RequestBody(
    content={
        'multipart/form-data': api_client.MediaType(
            schema=SchemaForRequestBodyMultipartFormData),
    },
    required=True,
)
SchemaFor200ResponseBodyApplicationJson = schemas.DictSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _upload_photo_mapped_args(
        self,
        api_key: str,
        photo: typing.IO,
        tags: typing.Optional[str] = None,
        title: typing.Optional[str] = None,
        description: typing.Optional[str] = None,
        content_type: typing.Optional[str] = None,
        hidden: typing.Optional[str] = None,
        is_family: typing.Optional[str] = None,
        is_friend: typing.Optional[str] = None,
        is_public: typing.Optional[str] = None,
        safety_level: typing.Optional[str] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _body = {}
        if tags is not None:
            _body["tags"] = tags
        if title is not None:
            _body["title"] = title
        if description is not None:
            _body["description"] = description
        if api_key is not None:
            _body["api_key"] = api_key
        if content_type is not None:
            _body["content_type"] = content_type
        if hidden is not None:
            _body["hidden"] = hidden
        if is_family is not None:
            _body["is_family"] = is_family
        if is_friend is not None:
            _body["is_friend"] = is_friend
        if is_public is not None:
            _body["is_public"] = is_public
        if photo is not None:
            _body["photo"] = photo
        if safety_level is not None:
            _body["safety_level"] = safety_level
        args.body = _body
        return args

    async def _aupload_photo_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'multipart/form-data',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/upload',
            body=body,
            headers=_headers,
        )
        serialized_data = request_body_public_upload_photo_request.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _upload_photo_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'multipart/form-data',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/upload',
            body=body,
            headers=_headers,
        )
        serialized_data = request_body_public_upload_photo_request.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class UploadPhotoRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aupload_photo(
        self,
        api_key: str,
        photo: typing.IO,
        tags: typing.Optional[str] = None,
        title: typing.Optional[str] = None,
        description: typing.Optional[str] = None,
        content_type: typing.Optional[str] = None,
        hidden: typing.Optional[str] = None,
        is_family: typing.Optional[str] = None,
        is_friend: typing.Optional[str] = None,
        is_public: typing.Optional[str] = None,
        safety_level: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._upload_photo_mapped_args(
            api_key=api_key,
            photo=photo,
            tags=tags,
            title=title,
            description=description,
            content_type=content_type,
            hidden=hidden,
            is_family=is_family,
            is_friend=is_friend,
            is_public=is_public,
            safety_level=safety_level,
        )
        return await self._aupload_photo_oapg(
            body=args.body,
            **kwargs,
        )
    
    def upload_photo(
        self,
        api_key: str,
        photo: typing.IO,
        tags: typing.Optional[str] = None,
        title: typing.Optional[str] = None,
        description: typing.Optional[str] = None,
        content_type: typing.Optional[str] = None,
        hidden: typing.Optional[str] = None,
        is_family: typing.Optional[str] = None,
        is_friend: typing.Optional[str] = None,
        is_public: typing.Optional[str] = None,
        safety_level: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._upload_photo_mapped_args(
            api_key=api_key,
            photo=photo,
            tags=tags,
            title=title,
            description=description,
            content_type=content_type,
            hidden=hidden,
            is_family=is_family,
            is_friend=is_friend,
            is_public=is_public,
            safety_level=safety_level,
        )
        return self._upload_photo_oapg(
            body=args.body,
        )

class UploadPhoto(BaseApi):

    async def aupload_photo(
        self,
        api_key: str,
        photo: typing.IO,
        tags: typing.Optional[str] = None,
        title: typing.Optional[str] = None,
        description: typing.Optional[str] = None,
        content_type: typing.Optional[str] = None,
        hidden: typing.Optional[str] = None,
        is_family: typing.Optional[str] = None,
        is_friend: typing.Optional[str] = None,
        is_public: typing.Optional[str] = None,
        safety_level: typing.Optional[str] = None,
        validate: bool = False,
        **kwargs,
    ) -> Dictionary:
        raw_response = await self.raw.aupload_photo(
            api_key=api_key,
            photo=photo,
            tags=tags,
            title=title,
            description=description,
            content_type=content_type,
            hidden=hidden,
            is_family=is_family,
            is_friend=is_friend,
            is_public=is_public,
            safety_level=safety_level,
            **kwargs,
        )
        if validate:
            return Dictionary(**raw_response.body)
        return api_client.construct_model_instance(Dictionary, raw_response.body)
    
    
    def upload_photo(
        self,
        api_key: str,
        photo: typing.IO,
        tags: typing.Optional[str] = None,
        title: typing.Optional[str] = None,
        description: typing.Optional[str] = None,
        content_type: typing.Optional[str] = None,
        hidden: typing.Optional[str] = None,
        is_family: typing.Optional[str] = None,
        is_friend: typing.Optional[str] = None,
        is_public: typing.Optional[str] = None,
        safety_level: typing.Optional[str] = None,
        validate: bool = False,
    ) -> Dictionary:
        raw_response = self.raw.upload_photo(
            api_key=api_key,
            photo=photo,
            tags=tags,
            title=title,
            description=description,
            content_type=content_type,
            hidden=hidden,
            is_family=is_family,
            is_friend=is_friend,
            is_public=is_public,
            safety_level=safety_level,
        )
        if validate:
            return Dictionary(**raw_response.body)
        return api_client.construct_model_instance(Dictionary, raw_response.body)


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        api_key: str,
        photo: typing.IO,
        tags: typing.Optional[str] = None,
        title: typing.Optional[str] = None,
        description: typing.Optional[str] = None,
        content_type: typing.Optional[str] = None,
        hidden: typing.Optional[str] = None,
        is_family: typing.Optional[str] = None,
        is_friend: typing.Optional[str] = None,
        is_public: typing.Optional[str] = None,
        safety_level: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._upload_photo_mapped_args(
            api_key=api_key,
            photo=photo,
            tags=tags,
            title=title,
            description=description,
            content_type=content_type,
            hidden=hidden,
            is_family=is_family,
            is_friend=is_friend,
            is_public=is_public,
            safety_level=safety_level,
        )
        return await self._aupload_photo_oapg(
            body=args.body,
            **kwargs,
        )
    
    def post(
        self,
        api_key: str,
        photo: typing.IO,
        tags: typing.Optional[str] = None,
        title: typing.Optional[str] = None,
        description: typing.Optional[str] = None,
        content_type: typing.Optional[str] = None,
        hidden: typing.Optional[str] = None,
        is_family: typing.Optional[str] = None,
        is_friend: typing.Optional[str] = None,
        is_public: typing.Optional[str] = None,
        safety_level: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._upload_photo_mapped_args(
            api_key=api_key,
            photo=photo,
            tags=tags,
            title=title,
            description=description,
            content_type=content_type,
            hidden=hidden,
            is_family=is_family,
            is_friend=is_friend,
            is_public=is_public,
            safety_level=safety_level,
        )
        return self._upload_photo_oapg(
            body=args.body,
        )

