# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from flickr_python_sdk import schemas  # noqa: F401


class PhotoEditability(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            canaddmeta = schemas.BoolSchema
            cancomment = schemas.BoolSchema
            __annotations__ = {
                "canaddmeta": canaddmeta,
                "cancomment": cancomment,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["canaddmeta"]) -> MetaOapg.properties.canaddmeta: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cancomment"]) -> MetaOapg.properties.cancomment: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["canaddmeta", "cancomment", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["canaddmeta"]) -> typing.Union[MetaOapg.properties.canaddmeta, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cancomment"]) -> typing.Union[MetaOapg.properties.cancomment, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["canaddmeta", "cancomment", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        canaddmeta: typing.Union[MetaOapg.properties.canaddmeta, bool, schemas.Unset] = schemas.unset,
        cancomment: typing.Union[MetaOapg.properties.cancomment, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PhotoEditability':
        return super().__new__(
            cls,
            *args,
            canaddmeta=canaddmeta,
            cancomment=cancomment,
            _configuration=_configuration,
            **kwargs,
        )
