# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from flickr_python_sdk import schemas  # noqa: F401


class PhotoPermissions(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            permaddmeta = schemas.StrSchema
            permcomment = schemas.StrSchema
            __annotations__ = {
                "permaddmeta": permaddmeta,
                "permcomment": permcomment,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["permaddmeta"]) -> MetaOapg.properties.permaddmeta: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["permcomment"]) -> MetaOapg.properties.permcomment: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["permaddmeta", "permcomment", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["permaddmeta"]) -> typing.Union[MetaOapg.properties.permaddmeta, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["permcomment"]) -> typing.Union[MetaOapg.properties.permcomment, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["permaddmeta", "permcomment", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        permaddmeta: typing.Union[MetaOapg.properties.permaddmeta, str, schemas.Unset] = schemas.unset,
        permcomment: typing.Union[MetaOapg.properties.permcomment, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PhotoPermissions':
        return super().__new__(
            cls,
            *args,
            permaddmeta=permaddmeta,
            permcomment=permcomment,
            _configuration=_configuration,
            **kwargs,
        )
