# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from flickr_python_sdk import schemas  # noqa: F401


class PhotoVisibility(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            isfamily = schemas.BoolSchema
            isfriend = schemas.BoolSchema
            ispublic = schemas.BoolSchema
            __annotations__ = {
                "isfamily": isfamily,
                "isfriend": isfriend,
                "ispublic": ispublic,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["isfamily"]) -> MetaOapg.properties.isfamily: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["isfriend"]) -> MetaOapg.properties.isfriend: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ispublic"]) -> MetaOapg.properties.ispublic: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["isfamily", "isfriend", "ispublic", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["isfamily"]) -> typing.Union[MetaOapg.properties.isfamily, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["isfriend"]) -> typing.Union[MetaOapg.properties.isfriend, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ispublic"]) -> typing.Union[MetaOapg.properties.ispublic, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["isfamily", "isfriend", "ispublic", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        isfamily: typing.Union[MetaOapg.properties.isfamily, bool, schemas.Unset] = schemas.unset,
        isfriend: typing.Union[MetaOapg.properties.isfriend, bool, schemas.Unset] = schemas.unset,
        ispublic: typing.Union[MetaOapg.properties.ispublic, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PhotoVisibility':
        return super().__new__(
            cls,
            *args,
            isfamily=isfamily,
            isfriend=isfriend,
            ispublic=ispublic,
            _configuration=_configuration,
            **kwargs,
        )
