# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from flickr_python_sdk import schemas  # noqa: F401


class PublicGetPhotoExifResponsePhoto(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            camera = schemas.StrSchema
        
            @staticmethod
            def exif() -> typing.Type['PublicGetPhotoExifResponsePhotoExif']:
                return PublicGetPhotoExifResponsePhotoExif
            farm = schemas.StrSchema
            id = schemas.StrSchema
            secret = schemas.StrSchema
            server = schemas.StrSchema
            __annotations__ = {
                "camera": camera,
                "exif": exif,
                "farm": farm,
                "id": id,
                "secret": secret,
                "server": server,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["camera"]) -> MetaOapg.properties.camera: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["exif"]) -> 'PublicGetPhotoExifResponsePhotoExif': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["farm"]) -> MetaOapg.properties.farm: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["secret"]) -> MetaOapg.properties.secret: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["server"]) -> MetaOapg.properties.server: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["camera", "exif", "farm", "id", "secret", "server", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["camera"]) -> typing.Union[MetaOapg.properties.camera, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["exif"]) -> typing.Union['PublicGetPhotoExifResponsePhotoExif', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["farm"]) -> typing.Union[MetaOapg.properties.farm, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["secret"]) -> typing.Union[MetaOapg.properties.secret, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["server"]) -> typing.Union[MetaOapg.properties.server, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["camera", "exif", "farm", "id", "secret", "server", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        camera: typing.Union[MetaOapg.properties.camera, str, schemas.Unset] = schemas.unset,
        exif: typing.Union['PublicGetPhotoExifResponsePhotoExif', schemas.Unset] = schemas.unset,
        farm: typing.Union[MetaOapg.properties.farm, str, schemas.Unset] = schemas.unset,
        id: typing.Union[MetaOapg.properties.id, str, schemas.Unset] = schemas.unset,
        secret: typing.Union[MetaOapg.properties.secret, str, schemas.Unset] = schemas.unset,
        server: typing.Union[MetaOapg.properties.server, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PublicGetPhotoExifResponsePhoto':
        return super().__new__(
            cls,
            *args,
            camera=camera,
            exif=exif,
            farm=farm,
            id=id,
            secret=secret,
            server=server,
            _configuration=_configuration,
            **kwargs,
        )

from flickr_python_sdk.model.public_get_photo_exif_response_photo_exif import PublicGetPhotoExifResponsePhotoExif
