# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from flickr_python_sdk import schemas  # noqa: F401


class PublicGetPhotoSizesResponseSizes(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            canblog = schemas.NumberSchema
            candownload = schemas.NumberSchema
            canprint = schemas.NumberSchema
            
            
            class sizes(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['Size']:
                        return Size
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['Size'], typing.List['Size']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'sizes':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'Size':
                    return super().__getitem__(i)
            __annotations__ = {
                "canblog": canblog,
                "candownload": candownload,
                "canprint": canprint,
                "sizes": sizes,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["canblog"]) -> MetaOapg.properties.canblog: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["candownload"]) -> MetaOapg.properties.candownload: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["canprint"]) -> MetaOapg.properties.canprint: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sizes"]) -> MetaOapg.properties.sizes: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["canblog", "candownload", "canprint", "sizes", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["canblog"]) -> typing.Union[MetaOapg.properties.canblog, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["candownload"]) -> typing.Union[MetaOapg.properties.candownload, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["canprint"]) -> typing.Union[MetaOapg.properties.canprint, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sizes"]) -> typing.Union[MetaOapg.properties.sizes, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["canblog", "candownload", "canprint", "sizes", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        canblog: typing.Union[MetaOapg.properties.canblog, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        candownload: typing.Union[MetaOapg.properties.candownload, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        canprint: typing.Union[MetaOapg.properties.canprint, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        sizes: typing.Union[MetaOapg.properties.sizes, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PublicGetPhotoSizesResponseSizes':
        return super().__new__(
            cls,
            *args,
            canblog=canblog,
            candownload=candownload,
            canprint=canprint,
            sizes=sizes,
            _configuration=_configuration,
            **kwargs,
        )

from flickr_python_sdk.model.size import Size
