# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from flickr_python_sdk import schemas  # noqa: F401


class TopicReply(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            author = schemas.StrSchema
            author_is_deleted = schemas.BoolSchema
            author_path_alias = schemas.StrSchema
            authorname = schemas.StrSchema
            can_delete = schemas.BoolSchema
            can_edit = schemas.BoolSchema
            datecreate = schemas.StrSchema
            iconfarm = schemas.StrSchema
            iconserver = schemas.StrSchema
            id = schemas.StrSchema
            is_pro = schemas.BoolSchema
            lastedit = schemas.StrSchema
        
            @staticmethod
            def message() -> typing.Type['TopicReplyMessage']:
                return TopicReplyMessage
            __annotations__ = {
                "author": author,
                "author_is_deleted": author_is_deleted,
                "author_path_alias": author_path_alias,
                "authorname": authorname,
                "can_delete": can_delete,
                "can_edit": can_edit,
                "datecreate": datecreate,
                "iconfarm": iconfarm,
                "iconserver": iconserver,
                "id": id,
                "is_pro": is_pro,
                "lastedit": lastedit,
                "message": message,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["author"]) -> MetaOapg.properties.author: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["author_is_deleted"]) -> MetaOapg.properties.author_is_deleted: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["author_path_alias"]) -> MetaOapg.properties.author_path_alias: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["authorname"]) -> MetaOapg.properties.authorname: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["can_delete"]) -> MetaOapg.properties.can_delete: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["can_edit"]) -> MetaOapg.properties.can_edit: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["datecreate"]) -> MetaOapg.properties.datecreate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["iconfarm"]) -> MetaOapg.properties.iconfarm: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["iconserver"]) -> MetaOapg.properties.iconserver: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["is_pro"]) -> MetaOapg.properties.is_pro: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["lastedit"]) -> MetaOapg.properties.lastedit: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["message"]) -> 'TopicReplyMessage': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["author", "author_is_deleted", "author_path_alias", "authorname", "can_delete", "can_edit", "datecreate", "iconfarm", "iconserver", "id", "is_pro", "lastedit", "message", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["author"]) -> typing.Union[MetaOapg.properties.author, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["author_is_deleted"]) -> typing.Union[MetaOapg.properties.author_is_deleted, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["author_path_alias"]) -> typing.Union[MetaOapg.properties.author_path_alias, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["authorname"]) -> typing.Union[MetaOapg.properties.authorname, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["can_delete"]) -> typing.Union[MetaOapg.properties.can_delete, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["can_edit"]) -> typing.Union[MetaOapg.properties.can_edit, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["datecreate"]) -> typing.Union[MetaOapg.properties.datecreate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["iconfarm"]) -> typing.Union[MetaOapg.properties.iconfarm, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["iconserver"]) -> typing.Union[MetaOapg.properties.iconserver, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["is_pro"]) -> typing.Union[MetaOapg.properties.is_pro, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["lastedit"]) -> typing.Union[MetaOapg.properties.lastedit, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["message"]) -> typing.Union['TopicReplyMessage', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["author", "author_is_deleted", "author_path_alias", "authorname", "can_delete", "can_edit", "datecreate", "iconfarm", "iconserver", "id", "is_pro", "lastedit", "message", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        author: typing.Union[MetaOapg.properties.author, str, schemas.Unset] = schemas.unset,
        author_is_deleted: typing.Union[MetaOapg.properties.author_is_deleted, bool, schemas.Unset] = schemas.unset,
        author_path_alias: typing.Union[MetaOapg.properties.author_path_alias, str, schemas.Unset] = schemas.unset,
        authorname: typing.Union[MetaOapg.properties.authorname, str, schemas.Unset] = schemas.unset,
        can_delete: typing.Union[MetaOapg.properties.can_delete, bool, schemas.Unset] = schemas.unset,
        can_edit: typing.Union[MetaOapg.properties.can_edit, bool, schemas.Unset] = schemas.unset,
        datecreate: typing.Union[MetaOapg.properties.datecreate, str, schemas.Unset] = schemas.unset,
        iconfarm: typing.Union[MetaOapg.properties.iconfarm, str, schemas.Unset] = schemas.unset,
        iconserver: typing.Union[MetaOapg.properties.iconserver, str, schemas.Unset] = schemas.unset,
        id: typing.Union[MetaOapg.properties.id, str, schemas.Unset] = schemas.unset,
        is_pro: typing.Union[MetaOapg.properties.is_pro, bool, schemas.Unset] = schemas.unset,
        lastedit: typing.Union[MetaOapg.properties.lastedit, str, schemas.Unset] = schemas.unset,
        message: typing.Union['TopicReplyMessage', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'TopicReply':
        return super().__new__(
            cls,
            *args,
            author=author,
            author_is_deleted=author_is_deleted,
            author_path_alias=author_path_alias,
            authorname=authorname,
            can_delete=can_delete,
            can_edit=can_edit,
            datecreate=datecreate,
            iconfarm=iconfarm,
            iconserver=iconserver,
            id=id,
            is_pro=is_pro,
            lastedit=lastedit,
            message=message,
            _configuration=_configuration,
            **kwargs,
        )

from flickr_python_sdk.model.topic_reply_message import TopicReplyMessage
