# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from flickr_python_sdk.paths.restmethodflickr_groups_pools_get_context.get import FlickrGroupsPoolsGetContext
from flickr_python_sdk.paths.oauth_access_token.get import GetAccessToken
from flickr_python_sdk.paths.restmethodflickr_photosets_get_photos.get import GetAlbumPhotos
from flickr_python_sdk.paths.restmethodflickr_favorites_get_list.get import GetFavoritePhotos
from flickr_python_sdk.paths.restmethodflickr_favorites_get_context.get import GetFavoritesContext
from flickr_python_sdk.paths.restmethodflickr_test_echo.get import GetFlickrTestEcho
from flickr_python_sdk.paths.restmethodflickr_galleries_get_photos.get import GetGalleryPhotos
from flickr_python_sdk.paths.restmethodflickr_groups_discuss_topics_get_list.get import GetGroupDiscussionTopics
from flickr_python_sdk.paths.restmethodflickr_groups_get_info.get import GetGroupInfo
from flickr_python_sdk.paths.restmethodflickr_groups_pools_get_photos.get import GetGroupPoolPhotos
from flickr_python_sdk.paths.restmethodflickr_groups_discuss_topics_get_info.get import GetGroupTopicInfo
from flickr_python_sdk.paths.restmethodflickr_groups_discuss_replies_get_info.get import GetGroupTopicRepliesInfo
from flickr_python_sdk.paths.oauth_request_token.get import GetOAuthToken
from flickr_python_sdk.paths.restmethodflickr_people_get_info.get import GetPersonInformation
from flickr_python_sdk.paths.restmethodflickr_photos_get_exif.get import GetPhotoExif
from flickr_python_sdk.paths.restmethodflickr_photos_get_info.get import GetPhotoInfo
from flickr_python_sdk.paths.restmethodflickr_photos_licenses_get_info.get import GetPhotoLicenses
from flickr_python_sdk.paths.restmethodflickr_photolist_get_context.get import GetPhotoListContext
from flickr_python_sdk.paths.restmethodflickr_photosets_get_context.get import GetPhotoSetContext
from flickr_python_sdk.paths.restmethodflickr_photos_get_sizes.get import GetPhotoSizes
from flickr_python_sdk.paths.restmethodflickr_photos_get_context.get import GetPhotostreamContext
from flickr_python_sdk.paths.restmethodflickr_photosets_get_list.get import GetUserAlbums
from flickr_python_sdk.paths.restmethodflickr_people_get_photos.get import GetUserPhotos
from flickr_python_sdk.paths.restmethodflickr_photos_search.get import SearchPhotos
from flickr_python_sdk.paths.upload.post import UploadPhoto
from flickr_python_sdk.apis.tags.public_api_raw import PublicApiRaw


class PublicApi(
    FlickrGroupsPoolsGetContext,
    GetAccessToken,
    GetAlbumPhotos,
    GetFavoritePhotos,
    GetFavoritesContext,
    GetFlickrTestEcho,
    GetGalleryPhotos,
    GetGroupDiscussionTopics,
    GetGroupInfo,
    GetGroupPoolPhotos,
    GetGroupTopicInfo,
    GetGroupTopicRepliesInfo,
    GetOAuthToken,
    GetPersonInformation,
    GetPhotoExif,
    GetPhotoInfo,
    GetPhotoLicenses,
    GetPhotoListContext,
    GetPhotoSetContext,
    GetPhotoSizes,
    GetPhotostreamContext,
    GetUserAlbums,
    GetUserPhotos,
    SearchPhotos,
    UploadPhoto,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PublicApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PublicApiRaw(api_client)
