# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from flickr_python_sdk.paths.restmethodflickr_groups_pools_get_context.get import FlickrGroupsPoolsGetContextRaw
from flickr_python_sdk.paths.oauth_access_token.get import GetAccessTokenRaw
from flickr_python_sdk.paths.restmethodflickr_photosets_get_photos.get import GetAlbumPhotosRaw
from flickr_python_sdk.paths.restmethodflickr_favorites_get_list.get import GetFavoritePhotosRaw
from flickr_python_sdk.paths.restmethodflickr_favorites_get_context.get import GetFavoritesContextRaw
from flickr_python_sdk.paths.restmethodflickr_test_echo.get import GetFlickrTestEchoRaw
from flickr_python_sdk.paths.restmethodflickr_galleries_get_photos.get import GetGalleryPhotosRaw
from flickr_python_sdk.paths.restmethodflickr_groups_discuss_topics_get_list.get import GetGroupDiscussionTopicsRaw
from flickr_python_sdk.paths.restmethodflickr_groups_get_info.get import GetGroupInfoRaw
from flickr_python_sdk.paths.restmethodflickr_groups_pools_get_photos.get import GetGroupPoolPhotosRaw
from flickr_python_sdk.paths.restmethodflickr_groups_discuss_topics_get_info.get import GetGroupTopicInfoRaw
from flickr_python_sdk.paths.restmethodflickr_groups_discuss_replies_get_info.get import GetGroupTopicRepliesInfoRaw
from flickr_python_sdk.paths.oauth_request_token.get import GetOAuthTokenRaw
from flickr_python_sdk.paths.restmethodflickr_people_get_info.get import GetPersonInformationRaw
from flickr_python_sdk.paths.restmethodflickr_photos_get_exif.get import GetPhotoExifRaw
from flickr_python_sdk.paths.restmethodflickr_photos_get_info.get import GetPhotoInfoRaw
from flickr_python_sdk.paths.restmethodflickr_photos_licenses_get_info.get import GetPhotoLicensesRaw
from flickr_python_sdk.paths.restmethodflickr_photolist_get_context.get import GetPhotoListContextRaw
from flickr_python_sdk.paths.restmethodflickr_photosets_get_context.get import GetPhotoSetContextRaw
from flickr_python_sdk.paths.restmethodflickr_photos_get_sizes.get import GetPhotoSizesRaw
from flickr_python_sdk.paths.restmethodflickr_photos_get_context.get import GetPhotostreamContextRaw
from flickr_python_sdk.paths.restmethodflickr_photosets_get_list.get import GetUserAlbumsRaw
from flickr_python_sdk.paths.restmethodflickr_people_get_photos.get import GetUserPhotosRaw
from flickr_python_sdk.paths.restmethodflickr_photos_search.get import SearchPhotosRaw
from flickr_python_sdk.paths.upload.post import UploadPhotoRaw


class PublicApiRaw(
    FlickrGroupsPoolsGetContextRaw,
    GetAccessTokenRaw,
    GetAlbumPhotosRaw,
    GetFavoritePhotosRaw,
    GetFavoritesContextRaw,
    GetFlickrTestEchoRaw,
    GetGalleryPhotosRaw,
    GetGroupDiscussionTopicsRaw,
    GetGroupInfoRaw,
    GetGroupPoolPhotosRaw,
    GetGroupTopicInfoRaw,
    GetGroupTopicRepliesInfoRaw,
    GetOAuthTokenRaw,
    GetPersonInformationRaw,
    GetPhotoExifRaw,
    GetPhotoInfoRaw,
    GetPhotoLicensesRaw,
    GetPhotoListContextRaw,
    GetPhotoSetContextRaw,
    GetPhotoSizesRaw,
    GetPhotostreamContextRaw,
    GetUserAlbumsRaw,
    GetUserPhotosRaw,
    SearchPhotosRaw,
    UploadPhotoRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
