# coding: utf-8

# flake8: noqa

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

__version__ = "1.0.0"

# import ApiClient
from flickr_python_sdk.api_client import ApiClient

# import Configuration
from flickr_python_sdk.configuration import Configuration

# import exceptions
from flickr_python_sdk.exceptions import OpenApiException
from flickr_python_sdk.exceptions import ApiAttributeError
from flickr_python_sdk.exceptions import ApiTypeError
from flickr_python_sdk.exceptions import ApiValueError
from flickr_python_sdk.exceptions import ApiKeyError
from flickr_python_sdk.exceptions import ApiException

from flickr_python_sdk.client import Flickr
