# coding: utf-8

"""
    Flickr API Schema

    A subset of Flickr's API defined in Swagger format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from flickr_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from flickr_python_sdk.api_response import AsyncGeneratorResponse
from flickr_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from flickr_python_sdk import schemas  # noqa: F401

from flickr_python_sdk.model.public_search_photos_response import PublicSearchPhotosResponse as PublicSearchPhotosResponseSchema

from flickr_python_sdk.type.public_search_photos_response import PublicSearchPhotosResponse

from ...api_client import Dictionary
from flickr_python_sdk.pydantic.public_search_photos_response import PublicSearchPhotosResponse as PublicSearchPhotosResponsePydantic

# Query params
ApiKeySchema = schemas.StrSchema
TextSchema = schemas.StrSchema
TagsSchema = schemas.StrSchema
UserIdSchema = schemas.StrSchema
MinUploadDateSchema = schemas.StrSchema
MaxUploadDateSchema = schemas.StrSchema
MinTakenDateSchema = schemas.StrSchema
MaxTakenDateSchema = schemas.StrSchema
LicenseSchema = schemas.StrSchema
SortSchema = schemas.StrSchema
PrivacyFilterSchema = schemas.NumberSchema
BboxSchema = schemas.StrSchema
AccuracySchema = schemas.StrSchema
SafeSearchSchema = schemas.NumberSchema
ContentTypeSchema = schemas.NumberSchema
MachineTagsSchema = schemas.StrSchema
MachineTagModeSchema = schemas.StrSchema
GroupIdSchema = schemas.StrSchema
ContactsSchema = schemas.StrSchema
WoeIdSchema = schemas.StrSchema
PlaceIdSchema = schemas.StrSchema
MediaSchema = schemas.StrSchema
HasGeoSchema = schemas.StrSchema
GeoContextSchema = schemas.StrSchema
LatSchema = schemas.StrSchema
LonSchema = schemas.StrSchema
RadiusSchema = schemas.NumberSchema
RadiusUnitsSchema = schemas.StrSchema
IsCommonsSchema = schemas.BoolSchema
InGallerySchema = schemas.BoolSchema
IsGettySchema = schemas.BoolSchema
PerPageSchema = schemas.NumberSchema
PageSchema = schemas.NumberSchema
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
        'api_key': typing.Union[ApiKeySchema, str, ],
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'text': typing.Union[TextSchema, str, ],
        'tags': typing.Union[TagsSchema, str, ],
        'user_id': typing.Union[UserIdSchema, str, ],
        'min_upload_date': typing.Union[MinUploadDateSchema, str, ],
        'max_upload_date': typing.Union[MaxUploadDateSchema, str, ],
        'min_taken_date': typing.Union[MinTakenDateSchema, str, ],
        'max_taken_date': typing.Union[MaxTakenDateSchema, str, ],
        'license': typing.Union[LicenseSchema, str, ],
        'sort': typing.Union[SortSchema, str, ],
        'privacy_filter': typing.Union[PrivacyFilterSchema, decimal.Decimal, int, float, ],
        'bbox': typing.Union[BboxSchema, str, ],
        'accuracy': typing.Union[AccuracySchema, str, ],
        'safe_search': typing.Union[SafeSearchSchema, decimal.Decimal, int, float, ],
        'content_type': typing.Union[ContentTypeSchema, decimal.Decimal, int, float, ],
        'machine_tags': typing.Union[MachineTagsSchema, str, ],
        'machine_tag_mode': typing.Union[MachineTagModeSchema, str, ],
        'group_id': typing.Union[GroupIdSchema, str, ],
        'contacts': typing.Union[ContactsSchema, str, ],
        'woe_id': typing.Union[WoeIdSchema, str, ],
        'place_id': typing.Union[PlaceIdSchema, str, ],
        'media': typing.Union[MediaSchema, str, ],
        'has_geo': typing.Union[HasGeoSchema, str, ],
        'geo_context': typing.Union[GeoContextSchema, str, ],
        'lat': typing.Union[LatSchema, str, ],
        'lon': typing.Union[LonSchema, str, ],
        'radius': typing.Union[RadiusSchema, decimal.Decimal, int, float, ],
        'radius_units': typing.Union[RadiusUnitsSchema, str, ],
        'is_commons': typing.Union[IsCommonsSchema, bool, ],
        'in_gallery': typing.Union[InGallerySchema, bool, ],
        'is_getty': typing.Union[IsGettySchema, bool, ],
        'per_page': typing.Union[PerPageSchema, decimal.Decimal, int, float, ],
        'page': typing.Union[PageSchema, decimal.Decimal, int, float, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_api_key = api_client.QueryParameter(
    name="api_key",
    style=api_client.ParameterStyle.FORM,
    schema=ApiKeySchema,
    required=True,
    explode=True,
)
request_query_text = api_client.QueryParameter(
    name="text",
    style=api_client.ParameterStyle.FORM,
    schema=TextSchema,
    explode=True,
)
request_query_tags = api_client.QueryParameter(
    name="tags",
    style=api_client.ParameterStyle.FORM,
    schema=TagsSchema,
    explode=True,
)
request_query_user_id = api_client.QueryParameter(
    name="user_id",
    style=api_client.ParameterStyle.FORM,
    schema=UserIdSchema,
    explode=True,
)
request_query_min_upload_date = api_client.QueryParameter(
    name="min_upload_date",
    style=api_client.ParameterStyle.FORM,
    schema=MinUploadDateSchema,
    explode=True,
)
request_query_max_upload_date = api_client.QueryParameter(
    name="max_upload_date",
    style=api_client.ParameterStyle.FORM,
    schema=MaxUploadDateSchema,
    explode=True,
)
request_query_min_taken_date = api_client.QueryParameter(
    name="min_taken_date",
    style=api_client.ParameterStyle.FORM,
    schema=MinTakenDateSchema,
    explode=True,
)
request_query_max_taken_date = api_client.QueryParameter(
    name="max_taken_date",
    style=api_client.ParameterStyle.FORM,
    schema=MaxTakenDateSchema,
    explode=True,
)
request_query_license = api_client.QueryParameter(
    name="license",
    style=api_client.ParameterStyle.FORM,
    schema=LicenseSchema,
    explode=True,
)
request_query_sort = api_client.QueryParameter(
    name="sort",
    style=api_client.ParameterStyle.FORM,
    schema=SortSchema,
    explode=True,
)
request_query_privacy_filter = api_client.QueryParameter(
    name="privacy_filter",
    style=api_client.ParameterStyle.FORM,
    schema=PrivacyFilterSchema,
    explode=True,
)
request_query_bbox = api_client.QueryParameter(
    name="bbox",
    style=api_client.ParameterStyle.FORM,
    schema=BboxSchema,
    explode=True,
)
request_query_accuracy = api_client.QueryParameter(
    name="accuracy",
    style=api_client.ParameterStyle.FORM,
    schema=AccuracySchema,
    explode=True,
)
request_query_safe_search = api_client.QueryParameter(
    name="safe_search",
    style=api_client.ParameterStyle.FORM,
    schema=SafeSearchSchema,
    explode=True,
)
request_query_content_type = api_client.QueryParameter(
    name="content_type",
    style=api_client.ParameterStyle.FORM,
    schema=ContentTypeSchema,
    explode=True,
)
request_query_machine_tags = api_client.QueryParameter(
    name="machine_tags",
    style=api_client.ParameterStyle.FORM,
    schema=MachineTagsSchema,
    explode=True,
)
request_query_machine_tag_mode = api_client.QueryParameter(
    name="machine_tag_mode",
    style=api_client.ParameterStyle.FORM,
    schema=MachineTagModeSchema,
    explode=True,
)
request_query_group_id = api_client.QueryParameter(
    name="group_id",
    style=api_client.ParameterStyle.FORM,
    schema=GroupIdSchema,
    explode=True,
)
request_query_contacts = api_client.QueryParameter(
    name="contacts",
    style=api_client.ParameterStyle.FORM,
    schema=ContactsSchema,
    explode=True,
)
request_query_woe_id = api_client.QueryParameter(
    name="woe_id",
    style=api_client.ParameterStyle.FORM,
    schema=WoeIdSchema,
    explode=True,
)
request_query_place_id = api_client.QueryParameter(
    name="place_id",
    style=api_client.ParameterStyle.FORM,
    schema=PlaceIdSchema,
    explode=True,
)
request_query_media = api_client.QueryParameter(
    name="media",
    style=api_client.ParameterStyle.FORM,
    schema=MediaSchema,
    explode=True,
)
request_query_has_geo = api_client.QueryParameter(
    name="has_geo",
    style=api_client.ParameterStyle.FORM,
    schema=HasGeoSchema,
    explode=True,
)
request_query_geo_context = api_client.QueryParameter(
    name="geo_context",
    style=api_client.ParameterStyle.FORM,
    schema=GeoContextSchema,
    explode=True,
)
request_query_lat = api_client.QueryParameter(
    name="lat",
    style=api_client.ParameterStyle.FORM,
    schema=LatSchema,
    explode=True,
)
request_query_lon = api_client.QueryParameter(
    name="lon",
    style=api_client.ParameterStyle.FORM,
    schema=LonSchema,
    explode=True,
)
request_query_radius = api_client.QueryParameter(
    name="radius",
    style=api_client.ParameterStyle.FORM,
    schema=RadiusSchema,
    explode=True,
)
request_query_radius_units = api_client.QueryParameter(
    name="radius_units",
    style=api_client.ParameterStyle.FORM,
    schema=RadiusUnitsSchema,
    explode=True,
)
request_query_is_commons = api_client.QueryParameter(
    name="is_commons",
    style=api_client.ParameterStyle.FORM,
    schema=IsCommonsSchema,
    explode=True,
)
request_query_in_gallery = api_client.QueryParameter(
    name="in_gallery",
    style=api_client.ParameterStyle.FORM,
    schema=InGallerySchema,
    explode=True,
)
request_query_is_getty = api_client.QueryParameter(
    name="is_getty",
    style=api_client.ParameterStyle.FORM,
    schema=IsGettySchema,
    explode=True,
)
request_query_per_page = api_client.QueryParameter(
    name="per_page",
    style=api_client.ParameterStyle.FORM,
    schema=PerPageSchema,
    explode=True,
)
request_query_page = api_client.QueryParameter(
    name="page",
    style=api_client.ParameterStyle.FORM,
    schema=PageSchema,
    explode=True,
)
SchemaFor200ResponseBodyApplicationJson = PublicSearchPhotosResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: PublicSearchPhotosResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: PublicSearchPhotosResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _search_photos_mapped_args(
        self,
        api_key: str,
        text: typing.Optional[str] = None,
        tags: typing.Optional[str] = None,
        user_id: typing.Optional[str] = None,
        min_upload_date: typing.Optional[str] = None,
        max_upload_date: typing.Optional[str] = None,
        min_taken_date: typing.Optional[str] = None,
        max_taken_date: typing.Optional[str] = None,
        license: typing.Optional[str] = None,
        sort: typing.Optional[str] = None,
        privacy_filter: typing.Optional[typing.Union[int, float]] = None,
        bbox: typing.Optional[str] = None,
        accuracy: typing.Optional[str] = None,
        safe_search: typing.Optional[typing.Union[int, float]] = None,
        content_type: typing.Optional[typing.Union[int, float]] = None,
        machine_tags: typing.Optional[str] = None,
        machine_tag_mode: typing.Optional[str] = None,
        group_id: typing.Optional[str] = None,
        contacts: typing.Optional[str] = None,
        woe_id: typing.Optional[str] = None,
        place_id: typing.Optional[str] = None,
        media: typing.Optional[str] = None,
        has_geo: typing.Optional[str] = None,
        geo_context: typing.Optional[str] = None,
        lat: typing.Optional[str] = None,
        lon: typing.Optional[str] = None,
        radius: typing.Optional[typing.Union[int, float]] = None,
        radius_units: typing.Optional[str] = None,
        is_commons: typing.Optional[bool] = None,
        in_gallery: typing.Optional[bool] = None,
        is_getty: typing.Optional[bool] = None,
        per_page: typing.Optional[typing.Union[int, float]] = None,
        page: typing.Optional[typing.Union[int, float]] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        if api_key is not None:
            _query_params["api_key"] = api_key
        if text is not None:
            _query_params["text"] = text
        if tags is not None:
            _query_params["tags"] = tags
        if user_id is not None:
            _query_params["user_id"] = user_id
        if min_upload_date is not None:
            _query_params["min_upload_date"] = min_upload_date
        if max_upload_date is not None:
            _query_params["max_upload_date"] = max_upload_date
        if min_taken_date is not None:
            _query_params["min_taken_date"] = min_taken_date
        if max_taken_date is not None:
            _query_params["max_taken_date"] = max_taken_date
        if license is not None:
            _query_params["license"] = license
        if sort is not None:
            _query_params["sort"] = sort
        if privacy_filter is not None:
            _query_params["privacy_filter"] = privacy_filter
        if bbox is not None:
            _query_params["bbox"] = bbox
        if accuracy is not None:
            _query_params["accuracy"] = accuracy
        if safe_search is not None:
            _query_params["safe_search"] = safe_search
        if content_type is not None:
            _query_params["content_type"] = content_type
        if machine_tags is not None:
            _query_params["machine_tags"] = machine_tags
        if machine_tag_mode is not None:
            _query_params["machine_tag_mode"] = machine_tag_mode
        if group_id is not None:
            _query_params["group_id"] = group_id
        if contacts is not None:
            _query_params["contacts"] = contacts
        if woe_id is not None:
            _query_params["woe_id"] = woe_id
        if place_id is not None:
            _query_params["place_id"] = place_id
        if media is not None:
            _query_params["media"] = media
        if has_geo is not None:
            _query_params["has_geo"] = has_geo
        if geo_context is not None:
            _query_params["geo_context"] = geo_context
        if lat is not None:
            _query_params["lat"] = lat
        if lon is not None:
            _query_params["lon"] = lon
        if radius is not None:
            _query_params["radius"] = radius
        if radius_units is not None:
            _query_params["radius_units"] = radius_units
        if is_commons is not None:
            _query_params["is_commons"] = is_commons
        if in_gallery is not None:
            _query_params["in_gallery"] = in_gallery
        if is_getty is not None:
            _query_params["is_getty"] = is_getty
        if per_page is not None:
            _query_params["per_page"] = per_page
        if page is not None:
            _query_params["page"] = page
        args.query = _query_params
        return args

    async def _asearch_photos_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_api_key,
            request_query_text,
            request_query_tags,
            request_query_user_id,
            request_query_min_upload_date,
            request_query_max_upload_date,
            request_query_min_taken_date,
            request_query_max_taken_date,
            request_query_license,
            request_query_sort,
            request_query_privacy_filter,
            request_query_bbox,
            request_query_accuracy,
            request_query_safe_search,
            request_query_content_type,
            request_query_machine_tags,
            request_query_machine_tag_mode,
            request_query_group_id,
            request_query_contacts,
            request_query_woe_id,
            request_query_place_id,
            request_query_media,
            request_query_has_geo,
            request_query_geo_context,
            request_query_lat,
            request_query_lon,
            request_query_radius,
            request_query_radius_units,
            request_query_is_commons,
            request_query_in_gallery,
            request_query_is_getty,
            request_query_per_page,
            request_query_page,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/rest?method=flickr.photos.search',
            headers=_headers,
        )
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _search_photos_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_api_key,
            request_query_text,
            request_query_tags,
            request_query_user_id,
            request_query_min_upload_date,
            request_query_max_upload_date,
            request_query_min_taken_date,
            request_query_max_taken_date,
            request_query_license,
            request_query_sort,
            request_query_privacy_filter,
            request_query_bbox,
            request_query_accuracy,
            request_query_safe_search,
            request_query_content_type,
            request_query_machine_tags,
            request_query_machine_tag_mode,
            request_query_group_id,
            request_query_contacts,
            request_query_woe_id,
            request_query_place_id,
            request_query_media,
            request_query_has_geo,
            request_query_geo_context,
            request_query_lat,
            request_query_lon,
            request_query_radius,
            request_query_radius_units,
            request_query_is_commons,
            request_query_in_gallery,
            request_query_is_getty,
            request_query_per_page,
            request_query_page,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/rest?method=flickr.photos.search',
            headers=_headers,
        )
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class SearchPhotosRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def asearch_photos(
        self,
        api_key: str,
        text: typing.Optional[str] = None,
        tags: typing.Optional[str] = None,
        user_id: typing.Optional[str] = None,
        min_upload_date: typing.Optional[str] = None,
        max_upload_date: typing.Optional[str] = None,
        min_taken_date: typing.Optional[str] = None,
        max_taken_date: typing.Optional[str] = None,
        license: typing.Optional[str] = None,
        sort: typing.Optional[str] = None,
        privacy_filter: typing.Optional[typing.Union[int, float]] = None,
        bbox: typing.Optional[str] = None,
        accuracy: typing.Optional[str] = None,
        safe_search: typing.Optional[typing.Union[int, float]] = None,
        content_type: typing.Optional[typing.Union[int, float]] = None,
        machine_tags: typing.Optional[str] = None,
        machine_tag_mode: typing.Optional[str] = None,
        group_id: typing.Optional[str] = None,
        contacts: typing.Optional[str] = None,
        woe_id: typing.Optional[str] = None,
        place_id: typing.Optional[str] = None,
        media: typing.Optional[str] = None,
        has_geo: typing.Optional[str] = None,
        geo_context: typing.Optional[str] = None,
        lat: typing.Optional[str] = None,
        lon: typing.Optional[str] = None,
        radius: typing.Optional[typing.Union[int, float]] = None,
        radius_units: typing.Optional[str] = None,
        is_commons: typing.Optional[bool] = None,
        in_gallery: typing.Optional[bool] = None,
        is_getty: typing.Optional[bool] = None,
        per_page: typing.Optional[typing.Union[int, float]] = None,
        page: typing.Optional[typing.Union[int, float]] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._search_photos_mapped_args(
            api_key=api_key,
            text=text,
            tags=tags,
            user_id=user_id,
            min_upload_date=min_upload_date,
            max_upload_date=max_upload_date,
            min_taken_date=min_taken_date,
            max_taken_date=max_taken_date,
            license=license,
            sort=sort,
            privacy_filter=privacy_filter,
            bbox=bbox,
            accuracy=accuracy,
            safe_search=safe_search,
            content_type=content_type,
            machine_tags=machine_tags,
            machine_tag_mode=machine_tag_mode,
            group_id=group_id,
            contacts=contacts,
            woe_id=woe_id,
            place_id=place_id,
            media=media,
            has_geo=has_geo,
            geo_context=geo_context,
            lat=lat,
            lon=lon,
            radius=radius,
            radius_units=radius_units,
            is_commons=is_commons,
            in_gallery=in_gallery,
            is_getty=is_getty,
            per_page=per_page,
            page=page,
        )
        return await self._asearch_photos_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def search_photos(
        self,
        api_key: str,
        text: typing.Optional[str] = None,
        tags: typing.Optional[str] = None,
        user_id: typing.Optional[str] = None,
        min_upload_date: typing.Optional[str] = None,
        max_upload_date: typing.Optional[str] = None,
        min_taken_date: typing.Optional[str] = None,
        max_taken_date: typing.Optional[str] = None,
        license: typing.Optional[str] = None,
        sort: typing.Optional[str] = None,
        privacy_filter: typing.Optional[typing.Union[int, float]] = None,
        bbox: typing.Optional[str] = None,
        accuracy: typing.Optional[str] = None,
        safe_search: typing.Optional[typing.Union[int, float]] = None,
        content_type: typing.Optional[typing.Union[int, float]] = None,
        machine_tags: typing.Optional[str] = None,
        machine_tag_mode: typing.Optional[str] = None,
        group_id: typing.Optional[str] = None,
        contacts: typing.Optional[str] = None,
        woe_id: typing.Optional[str] = None,
        place_id: typing.Optional[str] = None,
        media: typing.Optional[str] = None,
        has_geo: typing.Optional[str] = None,
        geo_context: typing.Optional[str] = None,
        lat: typing.Optional[str] = None,
        lon: typing.Optional[str] = None,
        radius: typing.Optional[typing.Union[int, float]] = None,
        radius_units: typing.Optional[str] = None,
        is_commons: typing.Optional[bool] = None,
        in_gallery: typing.Optional[bool] = None,
        is_getty: typing.Optional[bool] = None,
        per_page: typing.Optional[typing.Union[int, float]] = None,
        page: typing.Optional[typing.Union[int, float]] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._search_photos_mapped_args(
            api_key=api_key,
            text=text,
            tags=tags,
            user_id=user_id,
            min_upload_date=min_upload_date,
            max_upload_date=max_upload_date,
            min_taken_date=min_taken_date,
            max_taken_date=max_taken_date,
            license=license,
            sort=sort,
            privacy_filter=privacy_filter,
            bbox=bbox,
            accuracy=accuracy,
            safe_search=safe_search,
            content_type=content_type,
            machine_tags=machine_tags,
            machine_tag_mode=machine_tag_mode,
            group_id=group_id,
            contacts=contacts,
            woe_id=woe_id,
            place_id=place_id,
            media=media,
            has_geo=has_geo,
            geo_context=geo_context,
            lat=lat,
            lon=lon,
            radius=radius,
            radius_units=radius_units,
            is_commons=is_commons,
            in_gallery=in_gallery,
            is_getty=is_getty,
            per_page=per_page,
            page=page,
        )
        return self._search_photos_oapg(
            query_params=args.query,
        )

class SearchPhotos(BaseApi):

    async def asearch_photos(
        self,
        api_key: str,
        text: typing.Optional[str] = None,
        tags: typing.Optional[str] = None,
        user_id: typing.Optional[str] = None,
        min_upload_date: typing.Optional[str] = None,
        max_upload_date: typing.Optional[str] = None,
        min_taken_date: typing.Optional[str] = None,
        max_taken_date: typing.Optional[str] = None,
        license: typing.Optional[str] = None,
        sort: typing.Optional[str] = None,
        privacy_filter: typing.Optional[typing.Union[int, float]] = None,
        bbox: typing.Optional[str] = None,
        accuracy: typing.Optional[str] = None,
        safe_search: typing.Optional[typing.Union[int, float]] = None,
        content_type: typing.Optional[typing.Union[int, float]] = None,
        machine_tags: typing.Optional[str] = None,
        machine_tag_mode: typing.Optional[str] = None,
        group_id: typing.Optional[str] = None,
        contacts: typing.Optional[str] = None,
        woe_id: typing.Optional[str] = None,
        place_id: typing.Optional[str] = None,
        media: typing.Optional[str] = None,
        has_geo: typing.Optional[str] = None,
        geo_context: typing.Optional[str] = None,
        lat: typing.Optional[str] = None,
        lon: typing.Optional[str] = None,
        radius: typing.Optional[typing.Union[int, float]] = None,
        radius_units: typing.Optional[str] = None,
        is_commons: typing.Optional[bool] = None,
        in_gallery: typing.Optional[bool] = None,
        is_getty: typing.Optional[bool] = None,
        per_page: typing.Optional[typing.Union[int, float]] = None,
        page: typing.Optional[typing.Union[int, float]] = None,
        validate: bool = False,
        **kwargs,
    ) -> PublicSearchPhotosResponsePydantic:
        raw_response = await self.raw.asearch_photos(
            api_key=api_key,
            text=text,
            tags=tags,
            user_id=user_id,
            min_upload_date=min_upload_date,
            max_upload_date=max_upload_date,
            min_taken_date=min_taken_date,
            max_taken_date=max_taken_date,
            license=license,
            sort=sort,
            privacy_filter=privacy_filter,
            bbox=bbox,
            accuracy=accuracy,
            safe_search=safe_search,
            content_type=content_type,
            machine_tags=machine_tags,
            machine_tag_mode=machine_tag_mode,
            group_id=group_id,
            contacts=contacts,
            woe_id=woe_id,
            place_id=place_id,
            media=media,
            has_geo=has_geo,
            geo_context=geo_context,
            lat=lat,
            lon=lon,
            radius=radius,
            radius_units=radius_units,
            is_commons=is_commons,
            in_gallery=in_gallery,
            is_getty=is_getty,
            per_page=per_page,
            page=page,
            **kwargs,
        )
        if validate:
            return PublicSearchPhotosResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(PublicSearchPhotosResponsePydantic, raw_response.body)
    
    
    def search_photos(
        self,
        api_key: str,
        text: typing.Optional[str] = None,
        tags: typing.Optional[str] = None,
        user_id: typing.Optional[str] = None,
        min_upload_date: typing.Optional[str] = None,
        max_upload_date: typing.Optional[str] = None,
        min_taken_date: typing.Optional[str] = None,
        max_taken_date: typing.Optional[str] = None,
        license: typing.Optional[str] = None,
        sort: typing.Optional[str] = None,
        privacy_filter: typing.Optional[typing.Union[int, float]] = None,
        bbox: typing.Optional[str] = None,
        accuracy: typing.Optional[str] = None,
        safe_search: typing.Optional[typing.Union[int, float]] = None,
        content_type: typing.Optional[typing.Union[int, float]] = None,
        machine_tags: typing.Optional[str] = None,
        machine_tag_mode: typing.Optional[str] = None,
        group_id: typing.Optional[str] = None,
        contacts: typing.Optional[str] = None,
        woe_id: typing.Optional[str] = None,
        place_id: typing.Optional[str] = None,
        media: typing.Optional[str] = None,
        has_geo: typing.Optional[str] = None,
        geo_context: typing.Optional[str] = None,
        lat: typing.Optional[str] = None,
        lon: typing.Optional[str] = None,
        radius: typing.Optional[typing.Union[int, float]] = None,
        radius_units: typing.Optional[str] = None,
        is_commons: typing.Optional[bool] = None,
        in_gallery: typing.Optional[bool] = None,
        is_getty: typing.Optional[bool] = None,
        per_page: typing.Optional[typing.Union[int, float]] = None,
        page: typing.Optional[typing.Union[int, float]] = None,
        validate: bool = False,
    ) -> PublicSearchPhotosResponsePydantic:
        raw_response = self.raw.search_photos(
            api_key=api_key,
            text=text,
            tags=tags,
            user_id=user_id,
            min_upload_date=min_upload_date,
            max_upload_date=max_upload_date,
            min_taken_date=min_taken_date,
            max_taken_date=max_taken_date,
            license=license,
            sort=sort,
            privacy_filter=privacy_filter,
            bbox=bbox,
            accuracy=accuracy,
            safe_search=safe_search,
            content_type=content_type,
            machine_tags=machine_tags,
            machine_tag_mode=machine_tag_mode,
            group_id=group_id,
            contacts=contacts,
            woe_id=woe_id,
            place_id=place_id,
            media=media,
            has_geo=has_geo,
            geo_context=geo_context,
            lat=lat,
            lon=lon,
            radius=radius,
            radius_units=radius_units,
            is_commons=is_commons,
            in_gallery=in_gallery,
            is_getty=is_getty,
            per_page=per_page,
            page=page,
        )
        if validate:
            return PublicSearchPhotosResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(PublicSearchPhotosResponsePydantic, raw_response.body)


class ApiForget(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aget(
        self,
        api_key: str,
        text: typing.Optional[str] = None,
        tags: typing.Optional[str] = None,
        user_id: typing.Optional[str] = None,
        min_upload_date: typing.Optional[str] = None,
        max_upload_date: typing.Optional[str] = None,
        min_taken_date: typing.Optional[str] = None,
        max_taken_date: typing.Optional[str] = None,
        license: typing.Optional[str] = None,
        sort: typing.Optional[str] = None,
        privacy_filter: typing.Optional[typing.Union[int, float]] = None,
        bbox: typing.Optional[str] = None,
        accuracy: typing.Optional[str] = None,
        safe_search: typing.Optional[typing.Union[int, float]] = None,
        content_type: typing.Optional[typing.Union[int, float]] = None,
        machine_tags: typing.Optional[str] = None,
        machine_tag_mode: typing.Optional[str] = None,
        group_id: typing.Optional[str] = None,
        contacts: typing.Optional[str] = None,
        woe_id: typing.Optional[str] = None,
        place_id: typing.Optional[str] = None,
        media: typing.Optional[str] = None,
        has_geo: typing.Optional[str] = None,
        geo_context: typing.Optional[str] = None,
        lat: typing.Optional[str] = None,
        lon: typing.Optional[str] = None,
        radius: typing.Optional[typing.Union[int, float]] = None,
        radius_units: typing.Optional[str] = None,
        is_commons: typing.Optional[bool] = None,
        in_gallery: typing.Optional[bool] = None,
        is_getty: typing.Optional[bool] = None,
        per_page: typing.Optional[typing.Union[int, float]] = None,
        page: typing.Optional[typing.Union[int, float]] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._search_photos_mapped_args(
            api_key=api_key,
            text=text,
            tags=tags,
            user_id=user_id,
            min_upload_date=min_upload_date,
            max_upload_date=max_upload_date,
            min_taken_date=min_taken_date,
            max_taken_date=max_taken_date,
            license=license,
            sort=sort,
            privacy_filter=privacy_filter,
            bbox=bbox,
            accuracy=accuracy,
            safe_search=safe_search,
            content_type=content_type,
            machine_tags=machine_tags,
            machine_tag_mode=machine_tag_mode,
            group_id=group_id,
            contacts=contacts,
            woe_id=woe_id,
            place_id=place_id,
            media=media,
            has_geo=has_geo,
            geo_context=geo_context,
            lat=lat,
            lon=lon,
            radius=radius,
            radius_units=radius_units,
            is_commons=is_commons,
            in_gallery=in_gallery,
            is_getty=is_getty,
            per_page=per_page,
            page=page,
        )
        return await self._asearch_photos_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def get(
        self,
        api_key: str,
        text: typing.Optional[str] = None,
        tags: typing.Optional[str] = None,
        user_id: typing.Optional[str] = None,
        min_upload_date: typing.Optional[str] = None,
        max_upload_date: typing.Optional[str] = None,
        min_taken_date: typing.Optional[str] = None,
        max_taken_date: typing.Optional[str] = None,
        license: typing.Optional[str] = None,
        sort: typing.Optional[str] = None,
        privacy_filter: typing.Optional[typing.Union[int, float]] = None,
        bbox: typing.Optional[str] = None,
        accuracy: typing.Optional[str] = None,
        safe_search: typing.Optional[typing.Union[int, float]] = None,
        content_type: typing.Optional[typing.Union[int, float]] = None,
        machine_tags: typing.Optional[str] = None,
        machine_tag_mode: typing.Optional[str] = None,
        group_id: typing.Optional[str] = None,
        contacts: typing.Optional[str] = None,
        woe_id: typing.Optional[str] = None,
        place_id: typing.Optional[str] = None,
        media: typing.Optional[str] = None,
        has_geo: typing.Optional[str] = None,
        geo_context: typing.Optional[str] = None,
        lat: typing.Optional[str] = None,
        lon: typing.Optional[str] = None,
        radius: typing.Optional[typing.Union[int, float]] = None,
        radius_units: typing.Optional[str] = None,
        is_commons: typing.Optional[bool] = None,
        in_gallery: typing.Optional[bool] = None,
        is_getty: typing.Optional[bool] = None,
        per_page: typing.Optional[typing.Union[int, float]] = None,
        page: typing.Optional[typing.Union[int, float]] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._search_photos_mapped_args(
            api_key=api_key,
            text=text,
            tags=tags,
            user_id=user_id,
            min_upload_date=min_upload_date,
            max_upload_date=max_upload_date,
            min_taken_date=min_taken_date,
            max_taken_date=max_taken_date,
            license=license,
            sort=sort,
            privacy_filter=privacy_filter,
            bbox=bbox,
            accuracy=accuracy,
            safe_search=safe_search,
            content_type=content_type,
            machine_tags=machine_tags,
            machine_tag_mode=machine_tag_mode,
            group_id=group_id,
            contacts=contacts,
            woe_id=woe_id,
            place_id=place_id,
            media=media,
            has_geo=has_geo,
            geo_context=geo_context,
            lat=lat,
            lon=lon,
            radius=radius,
            radius_units=radius_units,
            is_commons=is_commons,
            in_gallery=in_gallery,
            is_getty=is_getty,
            per_page=per_page,
            page=page,
        )
        return self._search_photos_oapg(
            query_params=args.query,
        )

